"""Ingest visual library resource: archaeological/artistic artifacts with images, dates, locations.
No theory or interpretation — just factual records for visual generation reference."""
import asyncio
import hashlib
import logging

import asyncpg

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

ARTIFACTS = [
    # === PRE-POTTERY NEOLITHIC / ANATOLIA ===
    {"title": "Göbekli Tepe Pillar Reliefs", "location": "Şanlıurfa, Turkey", "culture": "Pre-Pottery Neolithic", "region": "Anatolia", "date_start": -9600, "date_end": -8200, "date_label": "~9600–8200 BCE",
     "description": "Monumental T-shaped limestone pillars arranged in circular enclosures, carved with low and high relief of animals including foxes, boars, snakes, aurochs, cranes, and abstract symbols. Pillars stand up to 5.5 meters tall and weigh up to 10 tons. The carvings show naturalistic animal forms with no visible human dwellings — a ritual/ceremonial site predating agriculture."},
    {"title": "Göbekli Tepe Pillar 43 (Vulture Stone)", "location": "Şanlıurfa, Turkey", "culture": "Pre-Pottery Neolithic", "region": "Anatolia", "date_start": -9000, "date_end": -9000, "date_label": "~9000 BCE",
     "description": "A T-shaped pillar featuring a prominent vulture with outstretched wings, a headless human figure, a scorpion, and various other animal and geometric symbols carved in relief. The vulture holds a circular disc. Located in Enclosure D at Göbekli Tepe."},
    {"title": "Karahan Tepe Human Sculptures", "location": "Şanlıurfa, Turkey", "culture": "Pre-Pottery Neolithic", "region": "Anatolia", "date_start": -9000, "date_end": -8500, "date_label": "~9000 BCE+",
     "description": "Life-sized and larger carved human figures emerging from bedrock and stone pillars. Features include a seated male figure with detailed facial features, phallic pillars, and carved heads with distinct expressions. Carved from local limestone bedrock in situ. The site contains T-pillars similar to Göbekli Tepe plus unique human-form sculptures."},
    {"title": "Sayburç Narrative Relief", "location": "Şanlıurfa, Turkey", "culture": "Pre-Pottery Neolithic", "region": "Anatolia", "date_start": -9000, "date_end": -8500, "date_label": "~9000 BCE",
     "description": "A carved stone bench featuring a narrative scene: two human figures flanking animals. One figure holds a snake, the other grasps a phallus while facing a bull. Leopards appear on each end of the bench. This is considered one of the earliest known narrative relief sculptures depicting humans interacting with animals in a sequential scene."},
    {"title": "Nevali Çori T-Pillars", "location": "Şanlıurfa, Turkey", "culture": "Pre-Pottery Neolithic", "region": "Anatolia", "date_start": -8000, "date_end": -7500, "date_label": "~8000 BCE",
     "description": "T-shaped monolithic limestone pillars with carved human arms and hands in low relief, similar to Göbekli Tepe but smaller. The site also yielded a carved limestone head with a snake or braid motif rising from the crown, and bird sculptures. The site is now submerged under the Atatürk Dam reservoir."},

    # === LEVANT ===
    {"title": "Ain Ghazal Plaster Statues", "location": "Amman, Jordan", "culture": "Pre-Pottery Neolithic B", "region": "Levant", "date_start": -7200, "date_end": -6500, "date_label": "~7200–6500 BCE",
     "description": "Half-size human figures made from lime plaster over reed armatures. Features include flat bodies, stylized faces with large eyes outlined in bitumen, small mouths, and no ears. Found in two caches — some figures are two-headed. Among the oldest known large-scale human statues. Heights range 35–90 cm."},
    {"title": "Jericho Tower and Plastered Skulls", "location": "Tell es-Sultan, West Bank", "culture": "Pre-Pottery Neolithic A/B", "region": "Levant", "date_start": -8000, "date_end": -7000, "date_label": "~8000–7000 BCE",
     "description": "A stone tower 8.5 meters tall with internal staircase, attached to a stone wall surrounding ancient Jericho. The plastered skulls are real human skulls with plaster facial features modeled over them, shells placed in eye sockets, and painted details. Found beneath floors of dwellings — an ancestor veneration practice."},

    # === ÇATALHÖYÜK ===
    {"title": "Çatalhöyük Murals and Shrines", "location": "Konya, Turkey", "culture": "Neolithic", "region": "Anatolia", "date_start": -7500, "date_end": -5700, "date_label": "~7500–5700 BCE",
     "description": "Wall paintings on interior plaster surfaces depicting vultures with headless human figures, geometric patterns, hunting scenes with deer and aurochs, handprints, and a possible landscape/map showing the settlement with an erupting volcano (Hasan Dağ). Shrines contain modeled clay bull heads (bucrania) mounted on walls, relief sculptures of leopards, and a seated female figure flanked by felines (sometimes called the 'Seated Goddess')."},

    # === NORTH AFRICA ===
    {"title": "Nabta Playa Stone Circle", "location": "Nubian Desert, Egypt", "culture": "Neolithic Pastoral", "region": "North Africa", "date_start": -6000, "date_end": -5500, "date_label": "~6000 BCE",
     "description": "A ring of small standing stones approximately 4 meters in diameter with alignment stones pointing to astronomical features. One of the oldest known stone circles with possible astronomical alignments. Located in a now-dry lake basin (playa) in the Western Desert of Egypt, south of Aswan."},
    {"title": "Nabta Playa Cattle Burials", "location": "Nubian Desert, Egypt", "culture": "Neolithic Pastoral", "region": "North Africa", "date_start": -5500, "date_end": -5000, "date_label": "~5500 BCE",
     "description": "Ritual cattle burials in clay-lined chambers covered by stone tumuli. The cattle were placed in anatomical position. Associated with megalithic stone alignments and a complex of ceremonial structures. Evidence of early cattle cult practices in the Saharan Neolithic."},

    # === SAHARA ROCK ART ===
    {"title": 'Tassili n\'Ajjer "Round Head" Paintings', "location": "Tassili n'Ajjer, Algeria", "culture": "Saharan Neolithic", "region": "Sahara / North Africa", "date_start": -6000, "date_end": -4000, "date_label": "~6000 BCE",
     "description": "Large rock paintings in sandstone shelters featuring human figures with large, featureless round heads. Figures are often depicted floating or in ritual poses. Colors include ochre, white, and dark pigments. Some figures are over 3 meters tall. The 'Round Head' period is the earliest recognized painting phase at Tassili."},
    {"title": 'Tassili n\'Ajjer "Swimming Figures"', "location": "Tassili n'Ajjer, Algeria", "culture": "Saharan Neolithic", "region": "Sahara / North Africa", "date_start": -6000, "date_end": -4000, "date_label": "~6000 BCE",
     "description": "Rock paintings showing human figures in horizontal swimming-like poses. Part of the extensive Tassili n'Ajjer rock art complex containing over 15,000 paintings and engravings across the sandstone plateau. The swimming figures indicate the Sahara's former wetter climate when the region had lakes and rivers."},
    {"title": "Ennedi Plateau Rock Art", "location": "Ennedi Plateau, Chad", "culture": "Saharan Pastoral/Neolithic", "region": "Sahara / Central Africa", "date_start": -5000, "date_end": -2000, "date_label": "~5000 BCE",
     "description": "Thousands of rock paintings and engravings in sandstone shelters across the Ennedi massif. Subjects include cattle herds, horses, camels (later period), human figures, and wild animals. Styles range from early engravings to multi-colored paintings showing the transition from wet Sahara to desert conditions."},

    # === SOUTH ASIA CAVE ART ===
    {"title": "Bhimbetka Rock Paintings", "location": "Madhya Pradesh, India", "culture": "Mesolithic to Historic", "region": "South Asia", "date_start": -10000, "date_end": -1000, "date_label": "~10,000 BCE+",
     "description": "Over 750 rock shelters containing paintings spanning thousands of years. Earliest paintings show large animals — bison, elephants, tigers, rhinoceros — in dark red and green. Later periods add hunting scenes, communal dances, horse riders, battle scenes, and geometric symbols. Pigments used include manganese, hematite, and vegetable dyes."},

    # === EUROPEAN CAVE ART ===
    {"title": "Chauvet Cave Paintings", "location": "Ardèche, France", "culture": "Upper Paleolithic (Aurignacian)", "region": "Europe", "date_start": -30000, "date_end": -28000, "date_label": "~30,000 BCE",
     "description": "Some of the oldest known cave paintings. Rendered in charcoal and red ochre on limestone walls. Subjects include horses, aurochs, lions, rhinoceros, bears, mammoths, and a unique owl. Techniques include shading, perspective, stump-drawing, and use of the cave's natural contours for three-dimensional effect. A panel of charging lions shows movement through sequential images. Some 400+ animal figures across two main chambers."},
    {"title": "Lascaux Cave Paintings", "location": "Dordogne, France", "culture": "Upper Paleolithic (Magdalenian)", "region": "Europe", "date_start": -17000, "date_end": -15000, "date_label": "~17,000 BCE",
     "description": "Over 600 paintings and 1,500 engravings across multiple chambers. The Hall of the Bulls features four large black aurochs up to 5.2 meters long — the largest cave art animals known. Other sections include the Axial Gallery (horses, ibex, aurochs), the Shaft (a bird-headed man with a bison), and the Chamber of Felines. Pigments include iron oxide (red/yellow), manganese dioxide (black), and kaolin (white)."},
    {"title": "Altamira Cave Paintings", "location": "Cantabria, Spain", "culture": "Upper Paleolithic (Magdalenian)", "region": "Europe", "date_start": -15000, "date_end": -12000, "date_label": "~15,000 BCE",
     "description": "Polychrome ceiling paintings of bison, horses, deer, and boar in a low-ceilinged chamber. The bison are rendered in red ochre and charcoal with sophisticated shading and use of natural rock bulges for three-dimensional form. Approximately 25 polychrome figures on the ceiling plus engravings and black drawings throughout the cave. The first cave art to be recognized as Paleolithic (discovered 1879)."},

    # === EUROPEAN ROCK ART / PETROGLYPHS ===
    {"title": "Val Camonica Petroglyphs", "location": "Val Camonica, Lombardy, Italy", "culture": "Neolithic through Iron Age", "region": "Europe", "date_start": -8000, "date_end": -100, "date_label": "~8000 BCE+",
     "description": "Over 300,000 rock engravings spanning 8,000+ years on glacially smoothed rock surfaces. Subjects include deer, warriors, plowing scenes, houses, chariots, labyrinths, sun symbols, armed figures, and the famous 'Camunian rose.' Techniques include pecking and incision. UNESCO World Heritage Site — the first in Italy (1979)."},
    {"title": "Alta Rock Carvings", "location": "Alta, Norway", "culture": "Arctic Hunter-Gatherer", "region": "Scandinavia", "date_start": -5000, "date_end": -2000, "date_label": "~5000 BCE",
     "description": "Over 6,000 carvings pecked into flat rock surfaces near the fjord. Subjects include reindeer, elk, bears, boats, fishing scenes, fences/corrals, and human figures. Many carvings are at former shorelines now elevated by post-glacial land uplift. Today the carvings are highlighted with red paint for visibility. UNESCO World Heritage Site."},

    # === MEGALITHIC EUROPE ===
    {"title": "Newgrange Spiral Carvings", "location": "County Meath, Ireland", "culture": "Neolithic", "region": "Europe", "date_start": -3200, "date_end": -3000, "date_label": "~3200 BCE",
     "description": "A large passage tomb with the entrance marked by a massive kerbstone carved with triple spirals, lozenges, and concentric circles. The passage is aligned so that sunlight enters the roof box and illuminates the inner chamber on the winter solstice. Carved stones line the passage and chamber. The mound is 85 meters in diameter, faced with white quartz cobbles."},
    {"title": "Knowth Megalithic Art", "location": "County Meath, Ireland", "culture": "Neolithic", "region": "Europe", "date_start": -3000, "date_end": -2500, "date_label": "~3000 BCE",
     "description": "The largest collection of megalithic art in Western Europe. Over 300 decorated stones with motifs including spirals, concentric circles, serpentiform lines, crescents, and radial designs. Two passage tombs (east and west) within a large mound surrounded by 18 satellite tombs. Kerbstones are extensively carved on their visible faces."},
    {"title": "Stonehenge and Aubrey Holes", "location": "Wiltshire, England", "culture": "Neolithic to Bronze Age", "region": "Europe", "date_start": -3000, "date_end": -2000, "date_label": "~3000–2000 BCE",
     "description": "A circular monument of sarsen stone uprights and lintels (each 25 tons, 4 meters tall) surrounding smaller bluestones transported from Wales (250 km). The 56 Aubrey Holes form an outer ring possibly for timber posts or stones. Aligned with summer solstice sunrise and winter solstice sunset. Heel Stone stands outside the entrance. Surrounding landscape includes burial mounds, Avenue, and Cursus."},
    {"title": "Durrington Walls Settlement", "location": "Wiltshire, England", "culture": "Late Neolithic", "region": "Europe", "date_start": -2500, "date_end": -2400, "date_label": "~2500 BCE",
     "description": "A large henge enclosure (500 meters diameter) with timber circles (Southern and Northern Circles) and a settlement of small houses with plaster floors. Connected to the River Avon by an avenue. Abundant pig bones suggest seasonal feasting. Located 2 miles from Stonehenge and likely served as a habitation/feasting site for Stonehenge builders."},
    {"title": "Skara Brae Village", "location": "Orkney, Scotland", "culture": "Late Neolithic", "region": "Europe", "date_start": -3180, "date_end": -2500, "date_label": "~3000 BCE",
     "description": "A cluster of 8 stone-built houses connected by covered passages, preserved under sand dunes. Stone furniture includes bed platforms, dressers, storage boxes, and hearths — all in stone due to the treeless environment. Covered drains run beneath the settlement. Artifacts include carved stone balls, bone tools, and pottery (Grooved Ware)."},
    {"title": "Carnac Stones", "location": "Carnac, Brittany, France", "culture": "Neolithic", "region": "Europe", "date_start": -4500, "date_end": -3300, "date_label": "~4500 BCE",
     "description": "Over 3,000 standing stones (menhirs) arranged in parallel alignments stretching over 4 kilometers in three main groups: Ménec, Kermario, and Kerlescan. Stones range from 0.6 to 4 meters tall, generally increasing in height from east to west. Associated dolmens and tumuli in the surrounding area. The largest single concentration of standing stones in the world."},

    # === MESOPOTAMIA ===
    {"title": "Proto-Cuneiform Tablets", "location": "Uruk, Iraq", "culture": "Sumerian (Uruk IV period)", "region": "Mesopotamia", "date_start": -3300, "date_end": -3100, "date_label": "~3300 BCE",
     "description": "Clay tablets with pictographic signs impressed or incised into wet clay. Content is primarily administrative: grain quantities, livestock counts, land measurements, and ration distributions. Signs represent concrete objects (grain, cattle, fish) and quantities using circular impressions. Precursor to cuneiform script. Found in the Eanna temple precinct at Uruk."},
    {"title": "Uruk Pictograph Tablets", "location": "Uruk, Iraq", "culture": "Sumerian (Uruk III period)", "region": "Mesopotamia", "date_start": -3200, "date_end": -3000, "date_label": "~3200 BCE",
     "description": "Transitional tablets showing evolution from pictographic to early cuneiform. Signs are more standardized and abstract than Uruk IV tablets. Include word lists (lexical texts) organized by topic — the earliest known dictionaries. Tablets are small, flat, and roughly rectangular. Over 5,000 tablets recovered from Uruk."},
    {"title": "Warka Vase", "location": "Uruk, Iraq", "culture": "Sumerian (Uruk III period)", "region": "Mesopotamia", "date_start": -3200, "date_end": -3000, "date_label": "~3200 BCE",
     "description": "A carved alabaster vessel approximately 1 meter tall with three registers of relief carving. Bottom register: water and plants (barley, date palms). Middle register: a procession of nude males carrying offerings. Top register: a robed female figure (possibly Inanna) receiving offerings before temple furnishings. One of the earliest narrative relief sculptures. Looted in 2003, subsequently recovered."},
    {"title": "Cylinder Seal Impressions", "location": "Uruk/Ur/Nineveh, Iraq", "culture": "Sumerian through Neo-Babylonian", "region": "Mesopotamia", "date_start": -3000, "date_end": -500, "date_label": "~3000–500 BCE",
     "description": "Small stone cylinders (2–6 cm) engraved with intaglio scenes that produce relief impressions when rolled across wet clay. Subjects include worship scenes, mythological contests (hero grasping animals), banquet scenes, animal files, and divine figures with horned crowns. Materials include lapis lazuli, hematite, chalcedony, serpentine, and shell. Used to seal containers, doors, and documents."},
    {"title": "Royal Tomb of Ur Artifacts", "location": "Ur, Iraq", "culture": "Sumerian (Early Dynastic III)", "region": "Mesopotamia", "date_start": -2600, "date_end": -2500, "date_label": "~2600 BCE",
     "description": "Excavated by Leonard Woolley (1922–34). Tombs contained gold helmets, gold and lapis lazuli jewelry, bronze weapons, lyres, game boards, cylinder seals, and the bodies of attendants (human sacrifice). Queen Puabi's tomb included a gold headdress with gold leaves and lapis beads, a gold cup, and a cylindrical gold vessel. Found in the Royal Cemetery of Ur alongside approximately 2,000 other burials."},
    {"title": "Bull-Headed Lyre of Ur", "location": "Ur, Iraq", "culture": "Sumerian (Early Dynastic III)", "region": "Mesopotamia", "date_start": -2500, "date_end": -2400, "date_label": "~2500 BCE",
     "description": "A large lyre with a gold-covered bull's head with lapis lazuli beard and eyes. The sound box front panel shows inlaid shell plaques depicting: a hero grasping two human-headed bulls, a donkey playing a similar lyre, a bear steadying the instrument, a fox carrying a rattle and sistrum, and a scorpion-man. Wood body reconstructed from impressions in soil. Originally from PG 789 (King's Grave)."},
    {"title": "Standard of Ur", "location": "Ur, Iraq", "culture": "Sumerian (Early Dynastic III)", "region": "Mesopotamia", "date_start": -2600, "date_end": -2400, "date_label": "~2600 BCE",
     "description": "A trapezoidal box (21.6 x 49.5 cm) decorated with mosaic of shell, red limestone, and lapis lazuli set in bitumen. Two main panels: 'War' side shows chariots trampling enemies, infantry with cloaks and spears, and prisoners presented to a large king figure. 'Peace' side shows a banquet with seated figures drinking, a musician playing a lyre, and processions of people bringing animals and goods. Found in PG 779."},
    {"title": "Stele of the Vultures", "location": "Tello (ancient Girsu/Lagash), Iraq", "culture": "Sumerian (Early Dynastic III)", "region": "Mesopotamia", "date_start": -2450, "date_end": -2400, "date_label": "~2450 BCE",
     "description": "A limestone victory stele (1.8 m tall, fragmentary). One side shows the god Ningirsu holding enemies in a net and striking with a mace. The other side depicts king Eannatum leading a phalanx of soldiers with overlapping shields and spears, marching over fallen enemies. Vultures carry away the heads of the dead. Commemorates Lagash's victory over Umma. One of the earliest known historical documents in visual form."},
    {"title": "Victory Stele of Naram-Sin", "location": "Susa, Iran (originally Akkadian Empire)", "culture": "Akkadian", "region": "Mesopotamia", "date_start": -2250, "date_end": -2200, "date_label": "~2250 BCE",
     "description": "A 2-meter tall pink sandstone stele showing king Naram-Sin ascending a mountain, wearing a horned helmet (symbol of divinity), trampling fallen Lullubi enemies. He is depicted larger than all other figures (hierarchical scale). Above him are celestial symbols (stars/suns). Soldiers follow in orderly formation behind him. Trees grow on the mountainside. Taken to Susa as war trophy by Elamites circa 1150 BCE."},
    {"title": "Burney Relief (Queen of the Night)", "location": "Southern Iraq", "culture": "Old Babylonian", "region": "Mesopotamia", "date_start": -1800, "date_end": -1750, "date_label": "~1800 BCE",
     "description": "A clay plaque (49.5 x 37 cm) depicting a nude winged female figure with bird talons for feet, standing on two recumbent lions and flanked by owls. She wears a multi-horned headdress and holds ring-and-rod symbols. Originally painted — traces of red on body, black on wings and background, white on feathers. Identity debated: Ishtar, Ereshkigal, or Lilitu. Now in the British Museum."},
    {"title": "Kudurru Boundary Stones", "location": "Babylon and surrounding region, Iraq", "culture": "Kassite through Neo-Babylonian", "region": "Mesopotamia", "date_start": -1200, "date_end": -600, "date_label": "~1200 BCE",
     "description": "Carved stone monuments (typically 30–60 cm tall) recording royal land grants. Upper portions feature registers of divine symbols: Shamash (sun disc), Sin (crescent), Ishtar (star), Marduk (spade), Nabu (stylus), Ninhursag (omega symbol), Gula (dog), and others. Serpent and scorpion figures often appear along borders. Lower portions contain cuneiform text recording the grant terms and curses against violators."},
    {"title": "Assyrian Palace Reliefs", "location": "Nineveh and Nimrud, Iraq", "culture": "Neo-Assyrian", "region": "Mesopotamia", "date_start": -900, "date_end": -600, "date_label": "~900–600 BCE",
     "description": "Monumental gypsum wall slabs carved in low relief lining the walls of Assyrian palaces. Subjects include royal hunts (lion hunts of Ashurbanipal), military campaigns with siege engines and deportations, religious ceremonies with the king before sacred trees, tributaries bringing goods, and garden scenes. Panels from Nimrud (Ashurnasirpal II) and Nineveh (Sennacherib, Ashurbanipal) are among the finest examples of ancient Near Eastern art."},
    {"title": "Winged Genies Reliefs", "location": "Nimrud (Kalhu), Iraq", "culture": "Neo-Assyrian", "region": "Mesopotamia", "date_start": -700, "date_end": -600, "date_label": "~700 BCE",
     "description": "Gypsum relief panels depicting winged human figures (apkallu) holding pine cones and buckets, performing ritual gestures before stylized sacred trees. The figures wear elaborate robes, horned helmets, and have large detailed wings. They appear to be purifying or pollinating the tree. From the palace of Ashurnasirpal II at Nimrud and later Assyrian palaces."},
    {"title": "Lamassu Statues", "location": "Khorsabad and Nimrud, Iraq", "culture": "Neo-Assyrian", "region": "Mesopotamia", "date_start": -900, "date_end": -700, "date_label": "~900–700 BCE",
     "description": "Colossal stone gateway figures combining a human head with a bull or lion body and eagle wings. Carved from single blocks of gypsum, standing 3–5 meters tall and weighing up to 40 tons. Viewed from the front they appear standing; from the side, walking — achieved by carving five legs. Bearded human faces wear horned crowns. They guarded palace entrances as protective spirits."},

    # === EGYPT ===
    {"title": "Narmer Palette", "location": "Hierakonpolis, Egypt", "culture": "Predynastic/Early Dynastic Egyptian", "region": "Egypt", "date_start": -3100, "date_end": -3050, "date_label": "~3100 BCE",
     "description": "A shield-shaped ceremonial palette of siltstone (64 cm tall). One side shows King Narmer wearing the White Crown of Upper Egypt, striking a kneeling enemy with a mace while Horus holds a personified marshland. The reverse shows Narmer in the Red Crown of Lower Egypt inspecting decapitated enemies, and two intertwined serpopards (long-necked felines) forming the cosmetic grinding circle. One of the earliest depictions of an Egyptian king and possibly records the unification of Egypt."},
    {"title": "Saqqara Tomb Paintings", "location": "Saqqara, Egypt", "culture": "Old Kingdom Egyptian", "region": "Egypt", "date_start": -2500, "date_end": -2300, "date_label": "~2500 BCE",
     "description": "Painted tomb chapels (mastabas) of Old Kingdom officials near the Step Pyramid. Scenes include agricultural activities (plowing, harvesting, winnowing), cattle herding, fishing and fowling in marshes, bread and beer making, carpentry, metalworking, ship building, and banquet scenes with dancers and musicians. Painted in mineral pigments on plaster: red ochre, yellow ochre, malachite green, Egyptian blue, carbon black, and calcium white."},
    {"title": "Beni Hasan Tomb Scenes", "location": "Beni Hasan, Egypt", "culture": "Middle Kingdom Egyptian", "region": "Egypt", "date_start": -1900, "date_end": -1800, "date_label": "~1900 BCE",
     "description": "Rock-cut tombs of Middle Kingdom nomarchs (provincial governors) with painted walls showing wrestling sequences (over 200 wrestling pairs in Tomb of Baqet III), military scenes, hunting, daily life, and a famous depiction of Asiatic traders arriving with goods (Tomb of Khnumhotep II). Distinctive style with elongated figures and vibrant colors on the limestone walls."},
    {"title": "Great Pyramid Interior", "location": "Giza, Egypt", "culture": "Old Kingdom Egyptian", "region": "Egypt", "date_start": -2580, "date_end": -2560, "date_label": "~2580 BCE",
     "description": "Interior passages and chambers of the Great Pyramid of Khufu. Features include the Descending Passage, Ascending Passage, Grand Gallery (47 meters long, corbelled ceiling rising 8.6 meters), King's Chamber with five relieving chambers above and a red granite sarcophagus, Queen's Chamber with a corbelled niche, and two narrow 'air shafts' extending from each upper chamber toward the exterior. Constructed of approximately 2.3 million limestone blocks."},
    {"title": "Solar Boat (Khufu Ship)", "location": "Giza, Egypt", "culture": "Old Kingdom Egyptian", "region": "Egypt", "date_start": -2500, "date_end": -2450, "date_label": "~2500 BCE",
     "description": "A full-size cedar wood boat (43.6 meters long, 5.9 meters wide) found disassembled in a sealed pit beside the Great Pyramid. Over 1,200 pieces were reassembled. Features a curved hull, oars, a cabin structure, and deckhouse. Built without nails using mortise-and-tenon joints and rope lashings through sewing holes. Now housed in the Grand Egyptian Museum."},
    {"title": "Valley of the Kings Murals", "location": "Luxor (Thebes), Egypt", "culture": "New Kingdom Egyptian", "region": "Egypt", "date_start": -1500, "date_end": -1100, "date_label": "~1500 BCE",
     "description": "Painted walls and ceilings in royal tombs depicting the pharaoh's journey through the underworld (Duat). Scenes from funerary texts including the Amduat, Book of Gates, Book of Caverns, and Litany of Ra. Imagery includes solar barques, serpent guardians, hours of the night, judgment scenes, and the deceased king with various deities. Vivid mineral pigments on plastered limestone walls."},
    {"title": "Seti I Tomb Astronomical Ceiling", "location": "Valley of the Kings (KV17), Luxor, Egypt", "culture": "New Kingdom Egyptian", "region": "Egypt", "date_start": -1290, "date_end": -1279, "date_label": "~1300 BCE",
     "description": "The burial chamber ceiling of Seti I's tomb depicts constellations, decans (star groups for timekeeping), and astronomical figures. Northern constellations include Meskhetyu (Bull's Foreleg / Big Dipper) and a hippopotamus goddess. Star tables and decan lists divide the night into hours. Figures of deities stand on the celestial sphere. Painted in vivid blue, gold, and white on a dark background."},
    {"title": "Book of Caverns Reliefs", "location": "Valley of the Kings, Luxor, Egypt", "culture": "New Kingdom Egyptian (Ramesside)", "region": "Egypt", "date_start": -1300, "date_end": -1100, "date_label": "~1300 BCE",
     "description": "Wall reliefs and paintings depicting the six divisions of the underworld from the funerary text known as the Book of Caverns. Features the sun god Ra's journey through caverns containing the blessed dead and the damned. Punishment scenes show enemies upside down, bound, decapitated, or burning in pits of fire. The blessed dead stand upright in their sarcophagi. Found in tombs of Merenptah, Ramesses III, and later pharaohs."},
    {"title": "Temple of Karnak Reliefs", "location": "Luxor (Thebes), Egypt", "culture": "Egyptian (Middle Kingdom through Ptolemaic)", "region": "Egypt", "date_start": -2000, "date_end": -300, "date_label": "~2000–300 BCE",
     "description": "The largest temple complex in Egypt. Features include the Hypostyle Hall (134 columns up to 24 meters tall covered in painted relief), obelisks of Hatshepsut and Thutmose I, the Festival Hall of Thutmose III, pylons with battle scenes (Seti I and Ramesses II), the Sacred Lake, and colossal statues. Reliefs show ritual scenes, military victories (Battle of Kadesh), divine birth narratives, and offering ceremonies."},
    {"title": "Temple of Luxor", "location": "Luxor, Egypt", "culture": "New Kingdom Egyptian", "region": "Egypt", "date_start": -1400, "date_end": -1300, "date_label": "~1400 BCE",
     "description": "Built primarily by Amenhotep III and Ramesses II. Features include a grand colonnade of 14 papyrus columns (each 16 meters tall), a peristyle court, and the Opet Festival reliefs showing the annual procession of divine barques from Karnak to Luxor. Ramesses II's first pylon has reliefs of the Battle of Kadesh and colossal seated statues. An avenue of sphinxes connects it to Karnak (2.7 km)."},
    {"title": "Temple of Edfu", "location": "Edfu, Egypt", "culture": "Ptolemaic Egyptian", "region": "Egypt", "date_start": -237, "date_end": -57, "date_label": "~237–57 BCE",
     "description": "The best-preserved ancient Egyptian temple. Dedicated to Horus. Features a massive pylon (36 meters tall) with carved scenes of Ptolemy XII smiting enemies before Horus. Interior walls are covered in hieroglyphic texts and reliefs describing the temple's construction, the Myth of Horus and Seth (a sacred drama), and ritual procedures. A granite naos (shrine) in the sanctuary once housed the cult statue."},
    {"title": "Temple of Dendera Ceiling", "location": "Dendera, Egypt", "culture": "Ptolemaic/Roman Egyptian", "region": "Egypt", "date_start": -50, "date_end": 20, "date_label": "~50 BCE",
     "description": "The ceiling of the Hathor temple at Dendera features astronomical scenes including the famous Dendera Zodiac (a circular planisphere now in the Louvre), sky goddess Nut stretching across the ceiling, 36 decans, and processional boats of hours. The Hypostyle Hall ceiling shows vultures and solar discs. Colors are well preserved in dark interior chambers. Also contains crypts with reliefs sometimes misidentified as depicting 'light bulbs.'"},
    {"title": "Abydos Temple Reliefs", "location": "Abydos, Egypt", "culture": "New Kingdom Egyptian", "region": "Egypt", "date_start": -1300, "date_end": -1250, "date_label": "~1300 BCE",
     "description": "The Temple of Seti I at Abydos contains exceptionally fine painted bas-reliefs. Features include the Abydos King List (cartouches of 76 pharaohs), seven sanctuary chapels dedicated to different deities (Osiris, Isis, Horus, Amun, Ra-Horakhty, Ptah, and the deified Seti I), and the Osiris Complex with depictions of the Djed pillar raising ceremony. The relief style is considered the finest of the New Kingdom."},
    {"title": "Osireion Megalithic Structure", "location": "Abydos, Egypt", "culture": "New Kingdom Egyptian", "region": "Egypt", "date_start": -1300, "date_end": -1250, "date_label": "~1300 BCE",
     "description": "A subterranean temple behind the Temple of Seti I, built of massive red granite and sandstone blocks. Features a central hall with a rectangular island surrounded by a water channel, massive granite pillars, and astronomical ceiling decorations (Book of Nut, Book of Gates). The architecture uses cyclopean masonry with blocks weighing up to 100 tons. Now partially flooded by rising water table."},
    {"title": "Canopic Chest Decoration", "location": "Various sites, Egypt", "culture": "New Kingdom Egyptian", "region": "Egypt", "date_start": -1500, "date_end": -1000, "date_label": "~1500 BCE",
     "description": "Canopic chests held four canopic jars containing mummified organs. Chests are typically wooden, gilded, and painted with the four Sons of Horus (Imsety, Hapy, Duamutef, Qebehsenuef) and protective goddesses (Isis, Nephthys, Neith, Serqet). The most famous example is Tutankhamun's alabaster canopic chest with four miniature gold coffins inside. Jar lids are carved as human, baboon, jackal, and falcon heads."},
    {"title": "Book of the Dead Papyri", "location": "Various sites, Egypt", "culture": "New Kingdom through Ptolemaic Egyptian", "region": "Egypt", "date_start": -1500, "date_end": -50, "date_label": "~1500 BCE+",
     "description": "Illustrated papyrus scrolls placed with the dead containing spells for navigating the afterlife. Vignettes include the Weighing of the Heart scene (heart on scales against Ma'at's feather before Osiris, with Ammit the devourer waiting), the Field of Reeds (paradise), the deceased before various deities, and protective amulet diagrams. Painted in colored inks on papyrus sheets up to 20+ meters long. The Papyrus of Ani (British Museum) is the most famous example."},

    # === INDUS VALLEY ===
    {"title": "Mohenjo-Daro City Layout", "location": "Sindh, Pakistan", "culture": "Indus Valley Civilization (Mature Harappan)", "region": "South Asia / Indus Valley", "date_start": -2600, "date_end": -1900, "date_label": "~2600 BCE",
     "description": "A planned urban center covering approximately 250 hectares. Features a raised 'Citadel' mound (west) with public buildings and a lower residential area (east) with a grid street plan. Fired-brick construction throughout. Sophisticated drainage system with covered drains along streets and private bathrooms in houses. Population estimated at 40,000–80,000. One of the largest cities of the ancient world."},
    {"title": "Harappa Granary Complex", "location": "Harappa, Punjab, Pakistan", "culture": "Indus Valley Civilization (Mature Harappan)", "region": "South Asia / Indus Valley", "date_start": -2600, "date_end": -1900, "date_label": "~2600 BCE",
     "description": "Two rows of six granary platforms (each approximately 15 x 6 meters) built on a raised brick platform near the River Ravi. Ventilation channels run between and beneath the platforms. Nearby circular brick platforms with central holes served as grain-husking areas (wheat and barley chaff found). Workers' quarters with small two-room houses line the south side."},
    {"title": "Great Bath of Mohenjo-Daro", "location": "Mohenjo-Daro, Sindh, Pakistan", "culture": "Indus Valley Civilization", "region": "South Asia / Indus Valley", "date_start": -2500, "date_end": -2000, "date_label": "~2500 BCE",
     "description": "A large public water tank (12 x 7 meters, 2.4 meters deep) constructed of precisely fitted bricks sealed with natural bitumen (tar). Steps descend into the pool from the north and south. Surrounded by a colonnade of brick pillars and small rooms. Water supplied by a well and drained through a corbelled drain. Located on the Citadel mound. No comparable structure exists in the contemporary ancient world."},
    {"title": "Indus Valley Animal Seals", "location": "Mohenjo-Daro/Harappa, Pakistan", "culture": "Indus Valley Civilization", "region": "South Asia / Indus Valley", "date_start": -2600, "date_end": -1900, "date_label": "~2600 BCE",
     "description": "Square steatite (soapstone) seals (typically 2–3 cm) with intaglio-carved animals and undeciphered script. Animals include the unicorn bull (most common), zebu, elephant, rhinoceros, tiger, and water buffalo. Each seal has 4–5 signs of the Indus script above the animal. Used to stamp impressions in clay for sealing goods. Over 3,700 seals recovered."},
    {"title": "Pashupati Seal", "location": "Mohenjo-Daro, Pakistan", "culture": "Indus Valley Civilization", "region": "South Asia / Indus Valley", "date_start": -2300, "date_end": -2000, "date_label": "~2300 BCE",
     "description": "A steatite seal (3.56 x 3.53 cm) depicting a seated figure in a cross-legged posture with arms resting on knees and a horned headdress. The figure is surrounded by four animals: elephant, tiger, rhinoceros, and water buffalo, with two deer-like animals beneath the seat. Seven characters of Indus script appear at the top. Found in DK-G area of Mohenjo-Daro. Now in the National Museum, New Delhi."},
    {"title": "Dancing Girl Statue", "location": "Mohenjo-Daro, Pakistan", "culture": "Indus Valley Civilization", "region": "South Asia / Indus Valley", "date_start": -2500, "date_end": -2000, "date_label": "~2500 BCE",
     "description": "A bronze statuette (10.5 cm tall) of a young woman standing with her left leg slightly bent, right hand on her hip, left arm covered in bangles resting on her thigh. She wears a necklace and has her hair styled in a bun. Cast using the lost-wax technique. One of the earliest known bronze sculptures using this method. Now in the National Museum, New Delhi."},
    {"title": "Priest-King Statue", "location": "Mohenjo-Daro, Pakistan", "culture": "Indus Valley Civilization", "region": "South Asia / Indus Valley", "date_start": -2500, "date_end": -2000, "date_label": "~2500 BCE",
     "description": "A steatite bust (17.5 cm tall) of a bearded male figure with half-closed eyes, a fillet (headband) with a circular ornament, and a cloak decorated with a trefoil (three-leaf) pattern originally inlaid with red paste. The left shoulder is bare. The figure has a carefully groomed beard and an upper lip shaved clean. Found in the DK-G area of Mohenjo-Daro. Now in the National Museum, Karachi."},

    # === LATER SOUTH ASIA ===
    {"title": "Ajanta Cave Paintings", "location": "Aurangabad, Maharashtra, India", "culture": "Buddhist (Satavahana and Vakataka periods)", "region": "South Asia", "date_start": -200, "date_end": 480, "date_label": "~200 BCE+",
     "description": "30 rock-cut caves with paintings and sculptures spanning 700 years. Paintings depict Jataka tales (Buddha's previous lives), court scenes, processions, and nature. Technique includes tempera on a base of clay, cow dung, and rice husks applied to rock, with mineral pigments. Famous scenes include the 'Bodhisattva Padmapani' and 'Dying Princess.' The later caves (Vakataka period) show masterful shading and perspective. UNESCO World Heritage Site."},
    {"title": "Sanchi Gateway Reliefs", "location": "Sanchi, Madhya Pradesh, India", "culture": "Buddhist (Satavahana period)", "region": "South Asia", "date_start": -200, "date_end": -100, "date_label": "~200 BCE",
     "description": "Four ornamental stone gateways (toranas) at the Great Stupa. Elaborately carved with scenes from the Buddha's life and Jataka tales, though the Buddha himself is represented only by symbols (footprints, Bodhi tree, empty throne, wheel). Carvings include yakshis (tree spirits), elephants, lions, and lotus patterns. The gateways stand 10 meters tall with three architraves (crossbeams) supported by carved pillars."},
    {"title": "Bharhut Reliefs", "location": "Bharhut, Madhya Pradesh, India", "culture": "Buddhist (Shunga period)", "region": "South Asia", "date_start": -200, "date_end": -100, "date_label": "~200 BCE",
     "description": "Carved sandstone railing and gateway from a Buddhist stupa. Relief panels depict Jataka tales with narrative labels in Brahmi script, devotees worshipping Buddhist symbols (stupa, Bodhi tree, dharma wheel), yaksha and yakshi figures, and floral/geometric medallions. Style is flat, with figures shown in profile. Most fragments are now in the Indian Museum, Kolkata."},

    # === CHINA ===
    {"title": "Oracle Bone Inscriptions", "location": "Anyang (ancient Yin), Henan, China", "culture": "Shang Dynasty", "region": "East Asia / China", "date_start": -1200, "date_end": -1050, "date_label": "~1200 BCE",
     "description": "Ox scapulae and turtle plastrons (shells) with divination questions carved in early Chinese script. Questions cover war, harvests, weather, hunting, ancestor sacrifices, and royal pregnancies. The bones were heated until they cracked, and the cracks were interpreted as answers. Over 150,000 fragments recovered containing approximately 4,500 distinct characters. The earliest substantial corpus of Chinese writing."},
    {"title": "Shang Bronze Ding Vessels", "location": "Anyang and Zhengzhou, China", "culture": "Shang Dynasty", "region": "East Asia / China", "date_start": -1400, "date_end": -1050, "date_label": "~1400 BCE",
     "description": "Large ritual bronze cooking/offering vessels on three or four legs. Decorated with taotie masks (symmetrical animal-face motifs), dragons, birds, cicadas, and geometric thunder patterns (leiwen) in high relief. Cast using piece-mold technique unique to Chinese bronze production. The largest known example (Houmuwu Ding) weighs 833 kg and stands 1.33 meters tall. Used for ancestral sacrificial rituals."},
    {"title": "Sanxingdui Bronze Figures", "location": "Sanxingdui, Sichuan, China", "culture": "Ancient Shu Kingdom", "region": "East Asia / China", "date_start": -1200, "date_end": -1000, "date_label": "~1200 BCE",
     "description": "Bronze statues and heads found in two ritual pits. The Standing Figure (2.62 meters tall on pedestal) has exaggerated hands gripping a now-missing object. Bronze heads feature angular faces, almond eyes, and some are covered in gold foil. A large bronze tree (3.96 meters tall) with branches bearing fruit and birds. A bronze mask (1.38 meters wide) with protruding cylindrical eyes, elephant-trunk nose, and huge ears. Unlike any other known Chinese Bronze Age art."},
    {"title": "Sanxingdui Gold Mask", "location": "Sanxingdui, Sichuan, China", "culture": "Ancient Shu Kingdom", "region": "East Asia / China", "date_start": -1200, "date_end": -1000, "date_label": "~1200 BCE",
     "description": "A large gold mask (28 x 23 cm, weighing approximately 280 grams) hammered from gold sheet. Features wide-set eyes, straight nose, broad mouth with slightly upturned corners, and large ears. Found in 2021 excavations of Pit No. 5 alongside ivory, jade, and bronze artifacts. The largest and heaviest gold mask found at Sanxingdui. Gold sheet is approximately 0.2 mm thick."},
    {"title": "Liangzhu Jade Cong", "location": "Liangzhu, Zhejiang, China", "culture": "Liangzhu Culture", "region": "East Asia / China", "date_start": -3000, "date_end": -2300, "date_label": "~3000 BCE",
     "description": "Jade tubes with square exterior cross-sections and round interior holes. Surfaces are carved with stylized face/mask motifs combining animal and human features — the 'divine face' or 'spirit face' pattern. Heights range from a few centimeters to nearly 50 cm. Made from nephrite jade using string-sawing and abrasive drilling techniques without metal tools. Found in elite burials. Function is debated but the form was adopted across later Chinese cultures."},
    {"title": "Terracotta Army", "location": "Xi'an (ancient Chang'an), Shaanxi, China", "culture": "Qin Dynasty", "region": "East Asia / China", "date_start": -210, "date_end": -209, "date_label": "~210 BCE",
     "description": "An estimated 8,000 life-size terracotta warrior figures, 130 chariots, 520 horses, and 150 cavalry horses arranged in battle formation in three pits near Emperor Qin Shi Huang's mausoleum. Each figure has unique facial features, hairstyles, and expressions. Originally painted in vivid colors (now mostly faded). Infantry, archers, officers, generals, and acrobats represented. Figures are 1.8 meters average height. Weapons include real bronze swords, crossbow triggers, and spearheads."},
    {"title": "Mawangdui Silk Banner (T-shaped)", "location": "Changsha, Hunan, China", "culture": "Western Han Dynasty", "region": "East Asia / China", "date_start": -168, "date_end": -168, "date_label": "~168 BCE",
     "description": "A T-shaped painted silk banner (2.05 meters long) from the tomb of Lady Dai (Xin Zhui). Three registers depict: top — the celestial realm with the sun (containing a crow), moon (with a toad), dragons, and heavenly gates; middle — Lady Dai herself with attendants; bottom — the underworld supported by a giant figure standing on two fish. Painted in mineral pigments on silk. Found draped over the innermost coffin."},
    {"title": "Han Dynasty Tomb Murals", "location": "Various sites, China", "culture": "Han Dynasty", "region": "East Asia / China", "date_start": -200, "date_end": 200, "date_label": "~200 BCE+",
     "description": "Painted murals on brick and stone tomb walls. Subjects include celestial scenes (Fuxi and Nüwa with intertwined serpent tails), banquet scenes, chariots and horses, hunting, acrobatics, scenes of filial piety, and mythological figures (Queen Mother of the West / Xiwangmu). Techniques include painted plaster, stamped hollow tiles, and carved pictorial stones (huaxiangshi). Major sites include Dahuting, Mawangdui, and Mixian."},

    # === AEGEAN / GREEK ===
    {"title": "Knossos Bull-Leaping Fresco", "location": "Knossos, Crete, Greece", "culture": "Minoan", "region": "Aegean / Mediterranean", "date_start": -1600, "date_end": -1450, "date_label": "~1600 BCE",
     "description": "A wall painting (approximately 78 cm tall) depicting three figures and a bull in a bull-leaping scene. A figure grasps the horns, another somersaults over the bull's back, and a third stands behind the bull. The bull is rendered in a flying gallop pose. Women are painted white, men red-brown (Egyptian convention). Painted in the 'true' fresco technique (pigment on wet plaster). From the eastern wing of the Palace of Knossos."},
    {"title": "Akrotiri Frescoes", "location": "Akrotiri, Santorini (Thera), Greece", "culture": "Minoan (Cycladic)", "region": "Aegean / Mediterranean", "date_start": -1600, "date_end": -1500, "date_label": "~1600 BCE",
     "description": "Wall paintings preserved by volcanic ash from the Theran eruption. Include the Flotilla Fresco (a miniature procession of ships between two harbors with dolphins), Spring Fresco (swallows and lilies on volcanic rocks), Boxing Boys, Fisherman with blue-and-yellow fish, and the Saffron Gatherers with monkeys and women. Colors are remarkably well preserved. The settlement was buried under meters of pumice and ash."},
    {"title": "Mycenaean Warrior Vase", "location": "Mycenae, Greece", "culture": "Mycenaean", "region": "Aegean / Mediterranean", "date_start": -1200, "date_end": -1100, "date_label": "~1200 BCE",
     "description": "A large krater (mixing vessel, approximately 41 cm tall) painted with two files of soldiers in procession. Warriors wear horned helmets, carry round shields, and march with spears. A woman stands to the left raising her arm in farewell or lament. Painted in the Pictorial Style using dark paint on light ground. Found by Schliemann's excavations at Mycenae. Now in the National Archaeological Museum, Athens."},
    {"title": "Lion Gate", "location": "Mycenae, Greece", "culture": "Mycenaean", "region": "Aegean / Mediterranean", "date_start": -1250, "date_end": -1200, "date_label": "~1250 BCE",
     "description": "The main entrance to the citadel of Mycenae. A massive lintel stone (estimated 20 tons) supports a relieving triangle containing a carved limestone slab depicting two rampant lions flanking a central column (Minoan-style tapering column on a double altar base). The lions' heads (now missing) were attached separately and turned to face visitors. The gateway opening is 3 meters wide and 3 meters tall. Constructed of Cyclopean masonry."},
    {"title": "Greek Black-Figure Pottery", "location": "Athens and Corinth, Greece", "culture": "Archaic Greek", "region": "Mediterranean", "date_start": -620, "date_end": -480, "date_label": "~600 BCE",
     "description": "Ceramic vessels decorated by painting figures in black slip on the natural red-orange clay body, then incising details with a sharp tool. Subjects include mythological scenes (Heracles' labors, Trojan War), athletic competitions, symposia, and daily life. Key artists include Exekias (Ajax and Achilles gaming) and the Amasis Painter. Vessel types include amphorae, kraters, kylikes, and lekythoi."},
    {"title": "Greek Red-Figure Pottery", "location": "Athens, Greece", "culture": "Classical Greek", "region": "Mediterranean", "date_start": -530, "date_end": -300, "date_label": "~500 BCE",
     "description": "The reverse of black-figure technique: the background is painted black, leaving figures in the natural red clay color. Internal details are painted with a brush (rather than incised), allowing greater anatomical precision and expressive detail. Invented in Athens circa 530 BCE. Key artists include the Berlin Painter, Euphronios, and the Kleophrades Painter. Subjects expand to include domestic scenes, women, and theatrical performances."},
    {"title": "Delphi Bronze Charioteer", "location": "Delphi, Greece", "culture": "Classical Greek (Early)", "region": "Mediterranean", "date_start": -478, "date_end": -474, "date_label": "~470 BCE",
     "description": "A bronze statue (1.8 meters tall) of a chariot driver holding reins, part of a larger group including chariot, four horses, and a groom. He wears a long xystis (charioteer's robe) cinched at the waist with a simple belt. Inlaid glass and onyx eyes, copper eyelashes and lips, silver headband and teeth. Dedicated by Polyzalus of Gela to commemorate a Pythian Games victory. One of the finest surviving Greek bronze statues."},
    {"title": "Parthenon Friezes", "location": "Athens, Greece", "culture": "Classical Greek", "region": "Mediterranean", "date_start": -447, "date_end": -432, "date_label": "~440 BCE",
     "description": "A continuous Ionic frieze (160 meters long) running around the exterior of the Parthenon's inner building (cella), plus metopes on the outer Doric entablature. The Ionic frieze depicts the Panathenaic procession: horsemen, chariots, musicians, sacrificial animals, water-carriers, and marshals converging on a central scene of the peplos presentation. Metopes show Centauromachy, Amazonomachy, Gigantomachy, and Trojan War scenes. Carved in Pentelic marble under Pheidias's supervision."},

    # === ROMAN ===
    {"title": "Pompeii Frescoes (Villa of Mysteries)", "location": "Pompeii, Italy", "culture": "Roman", "region": "Mediterranean / Italy", "date_start": -60, "date_end": -50, "date_label": "~50 BCE",
     "description": "A continuous frieze of life-size figures on a deep red (Pompeian red) background in a room of the Villa of the Mysteries, just outside Pompeii's walls. Scenes depict a sequence involving a seated woman, a frightened girl, a silenic figure reading from a scroll, a winged female figure flagellating a kneeling woman, and a dancing maenad with cymbals. Twenty-nine figures total. Painted in the Second Style (architectural illusionism). Preserved by the eruption of Vesuvius in 79 CE."},
    {"title": "Pompeii Graffiti", "location": "Pompeii, Italy", "culture": "Roman", "region": "Mediterranean / Italy", "date_start": -100, "date_end": 79, "date_label": "~79 CE",
     "description": "Over 11,000 graffiti inscriptions scratched, painted, or charcoaled onto walls throughout Pompeii. Content includes election campaign slogans (dipinti), advertisements for gladiatorial games, love declarations, obscene drawings and texts, literary quotations (Virgil), shop signs, and personal insults. Written primarily in Latin with some Oscan and Greek. Preserved by the eruption of Vesuvius and providing a unique snapshot of everyday Roman life."},
    {"title": "Roman Lararium Shrines", "location": "Pompeii, Herculaneum, and Rome, Italy", "culture": "Roman", "region": "Mediterranean / Italy", "date_start": -100, "date_end": 300, "date_label": "~100 BCE",
     "description": "Household shrines (lararia) for domestic worship of the Lares (household guardian spirits), Penates (pantry gods), and the Genius of the paterfamilias. Formats range from simple wall niches with painted images to elaborate aedicula (miniature temple) structures with columns and pediments. Painted figures typically include two dancing Lares holding rhyta (drinking horns) flanking a central togated genius figure making an offering, with a serpent below (the protective spirit of the place)."},
    {"title": "Roman Mosaics", "location": "Various Mediterranean sites", "culture": "Roman", "region": "Mediterranean", "date_start": -200, "date_end": 400, "date_label": "~200 BCE+",
     "description": "Floor and wall decorations made from small stone, glass, and ceramic cubes (tesserae). Subjects include mythological scenes (Alexander Mosaic from Pompeii showing the Battle of Issus), marine life, geometric borders, gladiatorial combat, agricultural scenes, and theatrical masks. Opus vermiculatum uses tiny tesserae (1–4 mm) for painterly detail. Opus tessellatum uses larger pieces for geometric patterns. Major examples at Pompeii, Piazza Armerina (Sicily), Antioch, and Zeugma."},

    # === MESOAMERICA: OLMEC ===
    {"title": "Olmec Colossal Heads", "location": "San Lorenzo and La Venta, Veracruz/Tabasco, Mexico", "culture": "Olmec", "region": "Mesoamerica", "date_start": -1200, "date_end": -900, "date_label": "~1200–900 BCE",
     "description": "Seventeen known colossal basalt heads, 1.5 to 3.4 meters tall, weighing up to 50 tons. Each depicts a unique individual wearing a tight-fitting helmet-like headdress. Flat noses, full lips, and slightly crossed eyes are common features. The basalt was quarried from the Tuxtla Mountains and transported up to 80 km without wheeled vehicles or draft animals. Ten are from San Lorenzo, four from La Venta, two from Tres Zapotes, one from Cobata."},
    {"title": "Olmec Jade Celts", "location": "La Venta and Guerrero, Mexico", "culture": "Olmec", "region": "Mesoamerica", "date_start": -1000, "date_end": -600, "date_label": "~1000 BCE",
     "description": "Polished jade and serpentine celts (axe-shaped objects) carved with incised designs of the Olmec supernatural — a were-jaguar motif combining infant human and jaguar features: downturned mouth, V-shaped cranial cleft, and flame-shaped eyebrows. The Kunz Axe (American Museum of Natural History) is 28 cm tall and depicts a full were-jaguar figure. Jade was the most valued material in Mesoamerica, sourced from the Motagua Valley in Guatemala."},
    {"title": "La Venta Altars (Thrones)", "location": "La Venta, Tabasco, Mexico", "culture": "Olmec", "region": "Mesoamerica", "date_start": -900, "date_end": -400, "date_label": "~900 BCE",
     "description": "Massive basalt monuments originally called altars but now interpreted as thrones. Altar 4 shows a seated figure emerging from a niche (earth-monster mouth) holding a rope connected to bound figures on the sides. Altar 5 depicts a figure holding a limp infant, with additional babies on the sides. Each weighs several tons. The niche represents a cave entrance to the supernatural realm. Major examples at La Venta Parque-Museo."},

    # === MESOAMERICA: INTERMEDIATE ===
    {"title": "Monte Albán Danzantes Reliefs", "location": "Monte Albán, Oaxaca, Mexico", "culture": "Zapotec", "region": "Mesoamerica", "date_start": -500, "date_end": -200, "date_label": "~500 BCE",
     "description": "Over 300 carved stone slabs depicting nude male figures in contorted postures originally thought to be dancers (danzantes). Now interpreted as slain captives — many show closed eyes, flowing blood scrolls, and genital mutilation. Associated glyphs may represent names or place names. Some of the earliest writing in Mesoamerica. Found set into the walls of Building L on the main platform of Monte Albán."},
    {"title": "Izapa Stelae", "location": "Izapa, Chiapas, Mexico", "culture": "Izapa/Epi-Olmec", "region": "Mesoamerica", "date_start": -300, "date_end": -50, "date_label": "~300 BCE",
     "description": "Carved stone stelae and altars with complex narrative scenes in low relief. Stela 5 (the 'Tree of Life' stela) shows a central world tree with multiple figures, water, and celestial elements. Other stelae depict deities, descending figures from the sky, boat scenes, and figures interacting with serpent and crocodilian creatures. The style bridges Olmec and later Maya art. Paired stelae-and-altar arrangements face towards Tacana volcano."},

    # === MESOAMERICA: TEOTIHUACAN ===
    {"title": "Teotihuacan Jaguar Murals", "location": "Teotihuacan, Mexico", "culture": "Teotihuacano", "region": "Mesoamerica", "date_start": -100, "date_end": 250, "date_label": "~100 BCE+",
     "description": "Wall paintings in residential and ceremonial compounds. The Jaguar Mural in the Palace of the Jaguars depicts felines in profile wearing feathered headdresses and blowing shell trumpets with speech scrolls. The Tepantitla murals show the 'Great Goddess' (or 'Tepantitla Mural') with a mountain/tree emerging from her head, flanked by priests casting seeds, and a lower register of small figures playing, swimming, and singing in a 'paradise' setting."},
    {"title": "Feathered Serpent Pyramid Sculptural Heads", "location": "Teotihuacan, Mexico", "culture": "Teotihuacano", "region": "Mesoamerica", "date_start": -200, "date_end": 200, "date_label": "~200 BCE+",
     "description": "The Feathered Serpent Pyramid (Temple of Quetzalcoatl) has facades covered with projecting carved stone heads alternating between a feathered serpent with an obsidian-inlaid collar and a goggle-eyed figure (Tlaloc or a fire serpent headdress). The serpent bodies undulate in low relief between the heads. Over 200 sacrificial burials found beneath and around the pyramid — individuals with hands bound behind their backs, shell necklaces, and pyrite mirrors."},

    # === MESOAMERICA: MAYA ===
    {"title": "Maya Hieroglyphic Stairway of Copán", "location": "Copán, Honduras", "culture": "Classic Maya", "region": "Mesoamerica", "date_start": -400, "date_end": 800, "date_label": "~400 BCE+",
     "description": "A monumental stone stairway with 63 steps containing over 1,800 individual glyph blocks — the longest known Maya hieroglyphic text. The text records the dynastic history of Copán from its founding to the reign of K'ak' Yipyaj Chan K'awiil (Smoke Shell). Five larger-than-life seated ruler statues are positioned at intervals on the stairway. Located on the west face of Structure 10L-26. Some blocks displaced by collapse."},
    {"title": "Maya Ball Court Reliefs", "location": "Various sites, Mesoamerica", "culture": "Maya (Classic period)", "region": "Mesoamerica", "date_start": -300, "date_end": 900, "date_label": "~300 BCE+",
     "description": "Carved stone panels and markers in Mesoamerican ball courts. At Chichén Itzá, the Great Ball Court panels show victorious team leaders holding a decapitated head while serpents of blood emerge from the victim's neck (six serpents transform into vegetation). Players wear heavy yokes (stone belt replicas), kneepads, and elaborate headdresses. Ball court markers from Copán and Toniná depict bound captives used as balls. Stone rings set high on the walls served as goals."},
    {"title": "Maya Painted Ceramic Scenes", "location": "Petén, Guatemala and surrounding regions", "culture": "Classic Maya", "region": "Mesoamerica", "date_start": -200, "date_end": 900, "date_label": "~200 BCE+",
     "description": "Polychrome painted vessels (vases, plates, bowls) depicting mythological narratives, palace scenes, ball games, warfare, and the Maize God's death and resurrection. Codex-style vessels (black and red on cream ground) show underworld scenes with death gods, jaguars, and skeletal figures. The 'Princeton Vase' shows a palace scene with a god smoking. The Kerr database catalogs over 1,500 rollout photographs of painted Maya ceramics."},
    {"title": "Maya Bloodletting Scenes", "location": "Yaxchilán and other Maya sites", "culture": "Classic Maya", "region": "Mesoamerica", "date_start": -300, "date_end": 800, "date_label": "~300 BCE+",
     "description": "Carved stone lintels depicting royal auto-sacrifice rituals. Yaxchilán Lintel 24 shows Lady K'ab'al Xook drawing a thorn-studded rope through her perforated tongue while her husband Shield Jaguar holds a torch above. Lintel 25 shows her subsequent vision of a serpent emerging from a bowl of blood-stained paper, with a warrior emerging from the serpent's jaws. Blood offerings activated communication with ancestors and deities."},
    {"title": "Palenque Sarcophagus Lid (Pacal)", "location": "Palenque, Chiapas, Mexico", "culture": "Classic Maya", "region": "Mesoamerica", "date_start": 683, "date_end": 683, "date_label": "683 CE",
     "description": "A carved limestone slab (3.8 x 2.2 meters) covering the sarcophagus of K'inich Janaab Pakal I in the Temple of the Inscriptions. The scene shows Pakal at the moment of death, falling into the maw of the earth monster (the underworld). A world tree (cross-shaped, a ceiba tree with a bird on top) rises from his body. Celestial and underworld serpents frame the scene. Border glyphs record dates and the names of Pakal's ancestors. The burial was discovered in 1952 by Alberto Ruz Lhuillier."},
    {"title": "Bonampak Murals", "location": "Bonampak, Chiapas, Mexico", "culture": "Classic Maya", "region": "Mesoamerica", "date_start": 790, "date_end": 792, "date_label": "~790 CE",
     "description": "Three rooms of continuous wall and vault paintings in Structure 1. Room 1: a royal court scene with musicians, dancers, and lords in elaborate costumes preparing for ceremony. Room 2: a battle scene showing capture of prisoners, followed by a scene of stripped captives displayed on pyramid steps with blood flowing from their fingers. Room 3: victory celebration with dancers on a pyramid platform, a royal woman performing bloodletting. Approximately 120 figures total. Colors include Maya blue, red, yellow, green, and black on lime plaster."},

    # === SOUTH AMERICA ===
    {"title": "Caral Sunken Plaza", "location": "Supe Valley, Peru", "culture": "Norte Chico (Caral)", "region": "South America / Andes", "date_start": -2600, "date_end": -2000, "date_label": "~2600 BCE",
     "description": "A circular sunken plaza (amphitheater) approximately 40 meters in diameter within the Caral complex. Stone-lined tiers descend into the central area. The complex includes six large platform mounds (pyramids) and a residential area. No pottery or evidence of warfare found. The oldest known urban center in the Americas. Radiocarbon-dated to approximately 2627 BCE."},
    {"title": "Caral Pyramid Complex", "location": "Supe Valley, Peru", "culture": "Norte Chico (Caral)", "region": "South America / Andes", "date_start": -2600, "date_end": -2000, "date_label": "~2600 BCE",
     "description": "Six large platform mounds, the largest (Pirámide Mayor) measuring 160 x 150 meters and 18 meters tall. Constructed of stone-filled shicra bags (woven reed mesh filled with rocks) stacked to form the core, faced with stone and plaster. An atrium, stairway, and fire pit on top. Quipu (knotted string recording devices) fragments found — the earliest known. No defensive walls. UNESCO World Heritage Site."},
    {"title": "Chavín Tenon Heads", "location": "Chavín de Huántar, Ancash, Peru", "culture": "Chavín", "region": "South America / Andes", "date_start": -900, "date_end": -200, "date_label": "~900 BCE",
     "description": "Stone heads with tenon (peg) projections that were inserted into the exterior walls of the Old Temple at Chavín. They depict human-feline transformation — features progress from fully human to fully jaguar/feline with fangs, wrinkled snouts, and snakes as hair. Approximately 40 heads survive. They may represent priests in stages of hallucinogen-induced transformation (San Pedro cactus use is documented at the site)."},
    {"title": "Chavín Underground Galleries", "location": "Chavín de Huántar, Peru", "culture": "Chavín", "region": "South America / Andes", "date_start": -900, "date_end": -200, "date_label": "~900 BCE",
     "description": "A labyrinth of narrow stone-lined passages within the temple platform. Ventilation ducts create acoustic effects — water channeled through ducts produces a roaring sound. The galleries are deliberately disorienting (tight passages, abrupt turns, dead ends). Designed to create a sensory experience for initiates. The Lanzón stands at a junction of interior passages. Light shafts and drainage channels are engineered into the structure."},
    {"title": "Lanzón Monolith", "location": "Chavín de Huántar, Peru", "culture": "Chavín", "region": "South America / Andes", "date_start": -900, "date_end": -500, "date_label": "~900 BCE",
     "description": "A blade-shaped granite monolith 4.53 meters tall set into the floor and ceiling of a cruciform gallery inside the Old Temple. Carved in low relief with a fanged anthropomorphic figure: upturned feline mouth with interlocking fangs, snakes as hair, clawed hands, one raised and one lowered. The figure's eyes look upward. The stone passes through a hole in the ceiling to the floor above, where offerings may have been poured down. The name 'lanzón' (great lance) refers to its shape."},
    {"title": "Paracas Burial Bundles", "location": "Paracas Peninsula, Ica, Peru", "culture": "Paracas", "region": "South America / Andes", "date_start": -800, "date_end": -200, "date_label": "~800 BCE",
     "description": "Mummy bundles from the Paracas Necropolis containing seated flexed bodies wrapped in layers of plain cotton cloth and elaborate embroidered mantles. Up to 40 textile layers per bundle, interspersed with offerings including gold ornaments, obsidian knives, spondylus shell, and ceramic vessels. Skulls often show trepanation (surgical bone removal) with evidence of healing. The bundles were placed in underground bottle-shaped tombs."},
    {"title": "Paracas Textiles", "location": "Paracas Peninsula, Peru", "culture": "Paracas", "region": "South America / Andes", "date_start": -700, "date_end": -200, "date_label": "~700 BCE",
     "description": "Among the finest pre-Columbian textiles. Embroidered mantles (up to 2.5 meters long) with hundreds of small figures in stem stitch and cross-knit loop stitch on plain-weave cotton ground. Motifs include a fanged supernatural being (the 'Oculate Being' with large round eyes), trophy heads, felines, birds, and composite creatures. Colors include over 190 distinct hues created from plant and insect dyes (including cochineal). Preserved by the extreme desert conditions."},
    {"title": "Nazca Geoglyphs (Nazca Lines)", "location": "Nazca Desert, Ica, Peru", "culture": "Nazca", "region": "South America / Andes", "date_start": -200, "date_end": 500, "date_label": "~200 BCE+",
     "description": "Hundreds of geoglyphs created by removing the dark oxidized surface pebbles to reveal the lighter ground beneath. Figures include a hummingbird (93 meters), spider (46 meters), monkey (55 meters with spiral tail), condor, whale, lizard, and various geometric lines and trapezoids extending up to several kilometers. Best viewed from the air or surrounding hills. Created over approximately 700 years. The desert's stable climate and lack of rain has preserved them."},
    {"title": "Moche Pottery Scenes", "location": "North Coast, Peru", "culture": "Moche (Mochica)", "region": "South America / Andes", "date_start": -100, "date_end": 700, "date_label": "~100 BCE+",
     "description": "Stirrup-spout ceramic vessels with modeled and painted scenes. Portrait vessels show individualized faces of rulers and warriors. Scene-bearing vessels depict ritual combat and capture, sexual acts, the 'Sacrifice Ceremony' (a lord receiving a goblet of blood from bound prisoners), deer hunts, runners carrying messenger bags, and supernatural beings. Fine-line painted vessels show complex narratives in orange and cream. Moche pottery is among the most naturalistic in the pre-Columbian Americas."},
    {"title": "Moche Sacrifice Murals", "location": "Huaca de la Luna, Trujillo, Peru", "culture": "Moche", "region": "South America / Andes", "date_start": -100, "date_end": 600, "date_label": "~100 BCE+",
     "description": "Polychrome murals on adobe walls of the Huaca de la Luna (Temple of the Moon). The main facade features repeated images of the 'Decapitator God' (Ai Apaec) — a fanged deity holding a tumi (ceremonial knife) and a severed head. Interior walls show processions of prisoners, warrior combat, and supernatural scenes. Multiple construction phases with murals painted over previous ones. Colors include red, white, yellow, black, and blue-gray on mud plaster."},

    # === AFRICA ===
    {"title": "Nok Terracotta Sculptures", "location": "Jos Plateau, Nigeria", "culture": "Nok Culture", "region": "West Africa", "date_start": -1500, "date_end": -500, "date_label": "~1500–1000 BCE",
     "description": "Terracotta human and animal figures, typically heads, ranging from 10 cm to nearly life-size. Distinctive features include triangular or D-shaped eyes with pierced pupils, elaborate hairstyles, and open mouths. Some full-body figures are seated or kneeling. Hollow construction with walls approximately 2–3 cm thick. Found in alluvial tin-mining deposits. The earliest known figurative sculpture tradition in sub-Saharan Africa. Associated with early iron smelting in West Africa."},
    {"title": "Axum (Aksum) Stelae", "location": "Axum, Tigray, Ethiopia", "culture": "Aksumite", "region": "East Africa / Horn of Africa", "date_start": -400, "date_end": 300, "date_label": "~400 BCE",
     "description": "Giant carved granite obelisks (stelae) in the ancient Aksumite capital. The tallest standing stele (Stele 3, 'King Ezana's Stele') is 24 meters tall. The fallen Great Stele (Stele 1) was 33 meters and approximately 520 tons — the largest single stone that ancient humans attempted to erect. Carved to resemble multi-story buildings with false doors and windows. Base plates with offering bowls suggest funerary purpose. UNESCO World Heritage Site."},
    {"title": "Nubian Pyramids of Meroë", "location": "Meroë, Sudan", "culture": "Kushite (Kingdom of Meroë)", "region": "Northeast Africa / Nubia", "date_start": -800, "date_end": 350, "date_label": "~800 BCE",
     "description": "Over 200 pyramids across three cemetery fields at Meroë, Nuri, and El-Kurru — more pyramids than Egypt. Steep-sided (approximately 70° angle) compared to Egyptian pyramids, rising 6–30 meters with small bases (approximately 8 meters wide). Built of sandstone blocks. Attached offering chapels on the east side contain carved reliefs showing the deceased before Osiris and other Egyptian-derived and local Nubian deities. Royal burials with gold jewelry, pottery, and glass objects."},

    # === AUSTRALIA / OCEANIA ===
    {"title": "Arnhem Land Rock Art", "location": "Arnhem Land, Northern Territory, Australia", "culture": "Aboriginal Australian", "region": "Australia / Oceania", "date_start": -20000, "date_end": 1900, "date_label": "~20,000 BCE+",
     "description": "One of the world's largest and oldest concentrations of rock art, spanning at least 20,000 years. Styles include early hand stencils, dynamic figures (small, animated human figures with elaborate headdresses), 'X-ray' style paintings showing internal organs and skeletal structure of animals, and large polychrome figures. Subjects include Barramundi fish, kangaroos, turtles, snakes (Rainbow Serpent), and mythological beings. Sites include Ubirr and Burrungkuy (Nourlangie)."},
    {"title": "Kakadu Rock Art", "location": "Kakadu National Park, Northern Territory, Australia", "culture": "Aboriginal Australian", "region": "Australia / Oceania", "date_start": -20000, "date_end": 1900, "date_label": "~20,000 BCE+",
     "description": "Over 5,000 documented rock art sites in the Kakadu region. Key sites include Ubirr with 'X-ray' paintings of fish, turtles, and a thylacine (now extinct on mainland), and Nourlangie Rock with a large Lightning Man (Namarrgon) figure surrounded by radiating lines. The art documents environmental change — earliest paintings show now-extinct megafauna, later paintings show European contact (ships, horses, guns). Paintings are created with ochre, kaolin, and charcoal."},
    {"title": "Wandjina Paintings", "location": "Kimberley, Western Australia", "culture": "Aboriginal Australian (Worrorra, Ngarinyin, Wunambul)", "region": "Australia / Oceania", "date_start": -4000, "date_end": 1900, "date_label": "~4000 BCE",
     "description": "Rock paintings of cloud and rain spirits with distinctive features: large round white faces without mouths, large dark eyes, and radiating lines or halos around the head. Bodies are often depicted as simple outlines with chest markings. Painted in white, red, black, and yellow pigments on cave and shelter walls. The Wandjina are still repainted in ceremony by Traditional Owners — a living art tradition. Images typically 1–3 meters tall."},
    {"title": "Bradshaw (Gwion Gwion) Rock Art", "location": "Kimberley, Western Australia", "culture": "Aboriginal Australian", "region": "Australia / Oceania", "date_start": -10000, "date_end": -4000, "date_label": "~10,000 BCE",
     "description": "Highly refined mulberry-colored paintings of slender human figures with detailed hair ornaments, tassels, arm bands, and elegant sashes. Figures are dynamic — running, dancing, hunting with boomerangs and multi-barbed spears. Painted with a fine brush in a distinct style unrelated to later Aboriginal X-ray or Wandjina traditions. Not repainted or maintained — they survive through a biofilm of living organisms (fungi/bacteria) that has replaced the original pigment over millennia."},

    # === OCEANIA ===
    {"title": "Nan Madol", "location": "Pohnpei, Federated States of Micronesia", "culture": "Saudeleur Dynasty", "region": "Oceania / Micronesia", "date_start": -200, "date_end": 1500, "date_label": "~200 BCE+",
     "description": "A megalithic city built on 92 artificial islets on a coral reef flat. Walls and platforms constructed of basalt 'logs' (prismatic columns formed naturally by cooling lava) stacked in header-and-stretcher courses, some weighing up to 50 tons. The islets cover an area of approximately 75 hectares. Madol Powe (the mortuary sector) contains royal tombs. Nandauwas is the central ceremonial enclosure with walls up to 7.6 meters tall. No quarry site on Pohnpei has been confirmed — the basalt columns may have been transported by raft from other parts of the island."},

    # === ANOMALOUS / MEGALITHIC ===
    {"title": "Baalbek Trilithon", "location": "Baalbek, Bekaa Valley, Lebanon", "culture": "Roman (on earlier Phoenician/Hellenistic foundation)", "region": "Levant / Near East", "date_start": -100, "date_end": 60, "date_label": "~100 BCE+",
     "description": "Three massive limestone blocks in the retaining wall of the Temple of Jupiter platform at Baalbek. Each measures approximately 19 x 4 x 3.6 meters and weighs an estimated 800 tons. A fourth unfinished block ('Stone of the Pregnant Woman') lies in a nearby quarry weighing approximately 1,000 tons, and a recently discovered fifth block weighs an estimated 1,650 tons — the largest worked stone in the ancient world. The blocks are fitted together without mortar, raised 7 meters above ground level."},
    {"title": "Puma Punku Stonework", "location": "Tiwanaku, La Paz, Bolivia", "culture": "Tiwanaku", "region": "South America / Andes", "date_start": 500, "date_end": 600, "date_label": "~500 CE",
     "description": "A platform mound with precisely cut andesite and red sandstone blocks featuring flat surfaces, sharp right angles, and interlocking H-shaped clamps cast from a copper-arsenic-nickel alloy. Some blocks have precise grooves and drill holes. The largest red sandstone block weighs approximately 131 tons. Andesite blocks were transported from quarries 10–90 km away. The site sits at 3,850 meters elevation on the Altiplano. Much of the original structure was dismantled for building material in colonial and modern times."},
]


async def main():
    pool = await asyncpg.create_pool(
        host="localhost", port=5432, user="eden", password="eden", database="eden",
        min_size=1, max_size=5,
    )

    async with pool.acquire() as conn:
        ts_id = await conn.fetchval(
            "SELECT id FROM trusted_sources WHERE slug = 'wikidata-artifacts'"
        )
        if not ts_id:
            ts_id = await conn.fetchval("SELECT id FROM trusted_sources ORDER BY created_at LIMIT 1")
        log.info("Using trusted_source_id: %s", ts_id)

    inserted = 0
    skipped = 0
    errors = 0

    for art in ARTIFACTS:
        ext_id = f"visual-lib-{art['title'].lower().replace(' ', '-').replace('/', '-')[:80]}"
        r2_key = f"visual-library/{ext_id}.json"
        title = art["title"]

        text = f"{art['title']}\n\nLocation: {art['location']}\nCulture: {art['culture']}\nRegion: {art['region']}\nDate: {art['date_label']}\n\n{art['description']}"
        checksum = hashlib.sha256(text.encode()).hexdigest()
        byte_size = len(text.encode("utf-8"))

        async with pool.acquire() as conn:
            existing = await conn.fetchval(
                "SELECT id FROM raw_objects WHERE external_id = $1", ext_id
            )
            if existing:
                log.info("  SKIP (exists): %s", title)
                skipped += 1
                continue

            try:
                async with conn.transaction():
                    ro_id = await conn.fetchval("""
                        INSERT INTO raw_objects (id, trusted_source_id, external_id, source_url,
                                                 content_type, checksum, byte_size, r2_key, fetched_at)
                        VALUES (gen_random_uuid(), $1, $2, $3, 'application/json', $4, $5, $6, NOW())
                        ON CONFLICT (r2_key) DO NOTHING RETURNING id
                    """, ts_id, ext_id, f"https://eden.internal/visual-library/{ext_id}",
                        checksum, byte_size, r2_key)
                    if not ro_id:
                        log.info("  SKIP (r2_key conflict): %s", title)
                        skipped += 1
                        continue

                    import json as _json
                    meta = _json.dumps({"region": art["region"], "date_label": art["date_label"], "artifact_type": "visual_reference"})
                    tsv_text = f"{title} {art['culture']} {art['location']} {art.get('region', '')} {art['description']}"

                    sr_id = await conn.fetchval("""
                        INSERT INTO source_records (id, raw_object_id, trusted_source_id, canonical_title,
                                                    culture, language_family, origin_place_name,
                                                    source_category, provenance_status, record_status,
                                                    metadata_jsonb, tsv,
                                                    created_at, updated_at)
                        VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, 'site_archive',
                                'verified', 'published',
                                $7::jsonb,
                                to_tsvector('english', $8),
                                NOW(), NOW())
                        RETURNING id
                    """, ro_id, ts_id, title, art["culture"], art.get("region", ""),
                        art["location"], meta, tsv_text)

                    await conn.execute("""
                        INSERT INTO source_versions (id, source_record_id, version_type, language,
                                                     is_preferred, copyright_status, text_extracted,
                                                     tsv,
                                                     created_at, updated_at)
                        VALUES (gen_random_uuid(), $1, 'museum_description', 'English',
                                true, 'public_domain', $2,
                                setweight(to_tsvector('english', $3), 'A') ||
                                to_tsvector('english', $2),
                                NOW(), NOW())
                    """, sr_id, text, title)

                    if art.get("date_start"):
                        await conn.execute("""
                            INSERT INTO source_dates (id, source_record_id, date_type, date_start, date_end,
                                                      date_label, dating_method, dating_confidence,
                                                      created_at, updated_at)
                            VALUES (gen_random_uuid(), $1, 'object_creation', $2, $3, $4,
                                    'archaeological', 'approximate', NOW(), NOW())
                        """, sr_id, art["date_start"], art.get("date_end", art["date_start"]),
                            art["date_label"])

                log.info("  OK: %s (%s)", title, art["date_label"])
                inserted += 1

            except Exception as e:
                log.error("  ERROR on %s: %s", title, e)
                errors += 1

    await pool.close()
    log.info("Done! Inserted: %d, Skipped: %d, Errors: %d", inserted, skipped, errors)


if __name__ == "__main__":
    asyncio.run(main())
